### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by sparrell** [ocsf/ocsf-docs#10]
I recommend adding a FAQs directory to this (ocsf-docs) directory. It could refer to other existing docs (eg the white papers, the contributing page, the governance page). One useful section would be on a series of questions on how OCSF relates to other activities (OCA, Mitre Att&ck,  STIX, CACAO, TAC, OpenC2, Kestrel, PACE, NIEM, ...).

**Comment by sparrell** [comment]
To the question of how it would work, initially just a README file in the FAQ directory with some reference in the main readme. 

Over time that might evolve to multiple files organized by type of question,with some questions rating their own pages (eg if it's a 'two pager' as opposed to a sentence or two.

Ideally eventually there would be a separate 'awareness and adoption' website, hopefully just a github repo with 'Pages' turned on and then besides FAQs there would be snazzier 'marketing' documentation.

But with crawl/walk/run - first you crawl with one file.

**Comment by pagbabian-splunk** [comment]
Merged the separate FAQs into a single doc.
