### ISSUE TITLE
Introduction: schema vs. data

### ISSUE THREAD

**Issue by davaya** [ocsf/ocsf-docs#21]
["Understanding OCSF"](https://github.com/ocsf/ocsf-docs/blob/main/Understanding%20OCSF.pdf) discusses personas at a high level, but in order to be "agnostic to storage format, data collection and ETL processes", an additional level of communication detail is required.  Being agnostic requires defining *what* information is collected, stored and transformed without regard to the *data formats* used to represent that information.

Current:

* The **author** persona is who creates or extends the schema.
* The **producer** persona is who generates events natively into the schema.
* The **mapper** persona is who translates or creates events from another source to the schema.
* The **analyst** persona is the end user who searches the data, writes rules or analytics against the schema, or creates reports from the schema.

The author works directly with the schema as described.  But producers, mappers and analysts work with data that corresponds to (can be validated by) the schema.

Proposed:

* The **producer** persona is who generates event data that is defined by (is valid according to) the schema.
* The **mapper** persona is who translates events from another source into data defined by the schema.
* The **analyst** persona is the end user who searches, writes rules or analytics for, or creates reports from data defined by the schema.

A communication diagram would show personas exchanging documents or messages, or in [NIEM terminology](http://niem.github.io/reference/iepd/), "Information Exchange Packages (IEPs) are the actual messages that carry data and are exchanged between stakeholders."  The schema itself is not a persona or communication endpoint, it is used by them when validating data or writing analytics.

**Comment by pagbabian-splunk** [comment]
Welcome improvements - I'll update and repost.  However I think someone had a suggestion to convert to a .md format and then it would be easier to keep things up today, via PRs etc.
