### ISSUE TITLE
Add a FAQ - What constitutes a breaking change in OCSF schema?

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-docs#30]
The topic that triggered this - Changing captions of an enum attribute is also a breaking change, since captions are used as values of the sibling string attributes.

We should create a FAQ to formalize what constitutes as a breaking change. We can use this issue to discuss and arrive at a consensus for what a breaking change for OCSF is.

**Comment by query-jeremy** [comment]
This can be closed.
