### ISSUE TITLE
timestamp_t value discrepency

### ISSUE THREAD

**Issue by sgolemon-corp** [ocsf/ocsf-docs#39]
https://github.com/ocsf/ocsf-docs/blob/main/Understanding%20OCSF.md documents the `timestamp_t` format as "milliseconds since the unix epoch", however the example payload provided by https://schema.ocsf.io/sample/1.2.0/classes/base_event produces a value for the `time` field in the quadrillions (e.g. `"time": 1718905365392963,`) which only makes sense if interpreted as **microseconds**, not **milliseconds**.

Is the error in the documentation, or the sample event implementation?

**Comment by sgolemon-corp** [comment]
Thanks! I assume this is best filed as a bug against schema.ocsf.io/sample, but I'm not sure where that repository lives. Do you happen to know?

**Comment by floydtree** [comment]
@sgolemon-corp those samples are generated by the OCSF server itself, if you can create an issue in the ocsf-server repo, that will be great. Thanks!
